'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Row = { id: string; key: string; value: string }
type Film = { id: string; title: string; slug: string; description: string; image_url: string; year: string; published: boolean }

export default function AdminEditor({ initialContent, initialFilms, messages }: { initialContent: Row[]; initialFilms: Film[]; messages: { id: string; name: string; email: string; message: string; status: string }[] }) {
  const [content, setContent] = useState(initialContent)
  const [films, setFilms] = useState(initialFilms)
  const supabase = createClient()
  async function saveContent(row: Row) { await supabase.from('site_content').upsert({ id: row.id, key: row.key, value: row.value, updated_at: new Date().toISOString() }) }
  async function saveFilm(film: Film) { await supabase.from('films').upsert({ ...film, updated_at: new Date().toISOString() }) }
  async function signOut() { await supabase.auth.signOut(); location.href = '/' }
  return <main className="mx-auto max-w-6xl px-5 pb-24 pt-32 md:px-10"><div className="mb-12 flex items-end justify-between"><div><p className="text-xs uppercase tracking-[.25em] text-muted-foreground">WUCH FILMS / CMS</p><h1 className="mt-4 font-serif text-6xl tracking-[-.06em]">Edit everything.</h1></div><button onClick={signOut} className="text-xs uppercase tracking-[.2em] text-muted-foreground">Sign out</button></div><section className="grid gap-12 lg:grid-cols-2"><div><h2 className="mb-5 font-serif text-3xl">Site content</h2><div className="space-y-3">{content.map((row, index) => <div key={row.id} className="border border-border p-4"><label className="text-[10px] uppercase tracking-[.2em] text-muted-foreground">{row.key}</label><textarea value={row.value} onChange={(e) => setContent(content.map((item, i) => i === index ? { ...item, value: e.target.value } : item))} onBlur={() => saveContent({ ...row, value: content[index].value })} className="mt-2 min-h-20 w-full resize-y bg-transparent text-sm outline-none" /></div>)}{content.length === 0 && <p className="text-sm text-muted-foreground">Add site_content rows in Supabase to edit copy here.</p>}</div></div><div><h2 className="mb-5 font-serif text-3xl">Films</h2><div className="space-y-4">{films.map((film, index) => <div key={film.id} className="space-y-3 border border-border p-4"><input value={film.title} onChange={(e) => setFilms(films.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} onBlur={() => saveFilm(films[index])} className="w-full bg-transparent font-serif text-2xl outline-none" /><input value={film.image_url} onChange={(e) => setFilms(films.map((item, i) => i === index ? { ...item, image_url: e.target.value } : item))} onBlur={() => saveFilm(films[index])} placeholder="Image URL" className="w-full border-b border-border bg-transparent py-2 text-sm outline-none" /><textarea value={film.description} onChange={(e) => setFilms(films.map((item, i) => i === index ? { ...item, description: e.target.value } : item))} onBlur={() => saveFilm(films[index])} className="min-h-20 w-full bg-transparent text-sm outline-none" /></div>)}{films.length === 0 && <p className="text-sm text-muted-foreground">No films yet. Add your first film row in Supabase.</p>}</div></div></section><section className="mt-16"><h2 className="mb-5 font-serif text-3xl">Contact submissions</h2><div className="space-y-3">{messages.map((message) => <article key={message.id} className="border border-border p-4"><div className="flex justify-between text-xs"><span>{message.name} · {message.email}</span><span className="uppercase tracking-widest text-muted-foreground">{message.status}</span></div><p className="mt-3 text-sm leading-6">{message.message}</p></article>)}{messages.length === 0 && <p className="text-sm text-muted-foreground">No enquiries yet.</p>}</div></section></main>
}
